sudo: required

language : generic

services:
  - docker

before_install:
  - echo "Start creating the image with dockerfile"
  - docker build -t elbum/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true elbum/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"