sudo: required

language : generic

services:
  - docker

before_install:
  - echo "Start creating the image with dockerfile"
  - docker build -t elbum/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true elbum/docker-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-842145777952"
  bucket_path: "docker-react-app"
  on:
    branch: main

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY

after_success:
  - echo "Test success v2"